#!/bin/bash

basedir=$(dirname $0)
account=eew_jp
url=http://api.twitter.com/1/statuses/user_timeline/$account.json
lastmessage_file=$basedir/.lastmessage

message=$(curl $url | json_xs | awk '/"text"/{text=$0}/"id"/{id=$3;exit}END{print id text;}')
touch $lastmessage_file
lastmessage=$(cat $lastmessage_file)

if [ "x$lastmessage" != "x$message" ]; then
	message_text=$(echo $message | sed -e 's/.*"text" : "\(.*\)",$/\1/')
	if [ "x$message_text" != "x" ]; then
		notify-send -c critical 緊急地震速報 "$message_text"
		echo "$message" > $lastmessage_file
	fi
fi

sleep 60
$0 &
